name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'tests/**'
  pull_request:
    branches: [main, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TestTemplate:

    runs-on: ubuntu-latest

    steps:
      - uses: tercen/actions/workflow-CI@main
        with:
          git-repository: ${GITHUB_REPOSITORY}
          # branch: main
          # tag: ''
          git-token: ${{ github.token }}
